-- MySQL Script generated by MySQL Workbench
-- Sun Feb  7 00:53:42 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdconectate
-- -----------------------------------------------------
-- Base de Datos de poryecto Conect-t
DROP SCHEMA IF EXISTS `bdconectate` ;

-- -----------------------------------------------------
-- Schema bdconectate
--
-- Base de Datos de poryecto Conect-t
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdconectate` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `bdconectate` ;

-- -----------------------------------------------------
-- Table `bdconectate`.`cat_sexo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdconectate`.`cat_sexo` ;

CREATE TABLE IF NOT EXISTS `bdconectate`.`cat_sexo` (
  `idsexo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL COMMENT 'descripcion',
  `ctrl_fecha_create` DATETIME NULL,
  `ctrl_fecha_update` DATETIME NOT NULL,
  `ctrl_user_mod` INT NOT NULL,
  PRIMARY KEY (`idsexo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdconectate`.`cat_edo_civil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdconectate`.`cat_edo_civil` ;

CREATE TABLE IF NOT EXISTS `bdconectate`.`cat_edo_civil` (
  `idedocivil` INT NOT NULL AUTO_INCREMENT,
  `edo_civil` VARCHAR(45) NOT NULL,
  `edo_desc` VARCHAR(200) NULL,
  `ctrl_fecha_create` DATETIME NULL,
  `ctrl_fecha_update` DATETIME NOT NULL,
  `ctrl_user_mod` INT NOT NULL,
  PRIMARY KEY (`idedocivil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdconectate`.`cat_status_congregante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdconectate`.`cat_status_congregante` ;

CREATE TABLE IF NOT EXISTS `bdconectate`.`cat_status_congregante` (
  `idstatus_con` INT NOT NULL AUTO_INCREMENT,
  `status_con_nom` VARCHAR(45) NOT NULL,
  `status_act` TINYINT NOT NULL COMMENT 'status dela opcion activo o inactivo 1 /0 ',
  `ctrl_fecha_create` DATETIME NULL,
  `ctrl_fecha_update` DATETIME NOT NULL,
  `ctrl_user_mod` INT NOT NULL,
  PRIMARY KEY (`idstatus_con`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdconectate`.`cat_nacionalidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdconectate`.`cat_nacionalidad` ;

CREATE TABLE IF NOT EXISTS `bdconectate`.`cat_nacionalidad` (
  `idnacion` INT NOT NULL AUTO_INCREMENT,
  `pais_nac` VARCHAR(150) NOT NULL,
  `gentilicio_nac` VARCHAR(150) NOT NULL,
  `iso_nac` VARCHAR(5) NOT NULL,
  `ctrl_fecha_create` DATETIME NULL,
  `ctrl_fecha_update` DATETIME NOT NULL,
  `ctrl_user_mod` INT NOT NULL,
  PRIMARY KEY (`idnacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdconectate`.`congregantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdconectate`.`congregantes` ;

CREATE TABLE IF NOT EXISTS `bdconectate`.`congregantes` (
  `idcon` INT NOT NULL AUTO_INCREMENT,
  `con_matricula` VARCHAR(10) NOT NULL COMMENT 'Matricula al registrar',
  `con_nombre` VARCHAR(100) NOT NULL COMMENT 'nombre del congregante ',
  `con_ap_pat` VARCHAR(100) NOT NULL COMMENT 'apellido paterno del congrgante',
  `con_ap_mat` VARCHAR(100) NULL COMMENT 'apellido materno del congrgante',
  `con_sexo` INT NOT NULL COMMENT 'sexo del congrante consulta catalago para seleccinar opcion',
  `con_edo_civil` INT NOT NULL COMMENT 'estado civil del congregante ',
  `con_status_con` INT NOT NULL COMMENT 'estatus del congregante activo , inactivo , finado , baja voluntaria',
  `con_nacionalidad` INT NOT NULL COMMENT 'nacionalidad del congregante',
  `con_servidor` TINYINT NOT NULL COMMENT 'bandera para saber si es servidor ',
  `con_fecha_nac` DATE NOT NULL COMMENT 'fecha de nacimiento del congregante',
  `ctrl_fecha_create` DATETIME NULL COMMENT 'fecha y hora del congregante al registrar',
  `ctrl_fecha_update` DATETIME NOT NULL COMMENT 'fecha y hora de la ultima actualizacion',
  `ctrl_user_mod` INT NOT NULL COMMENT 'usuario que hizo ultima actualizacion del registro',
  PRIMARY KEY (`idcon`),
  UNIQUE INDEX `idcon_UNIQUE` (`idcon` ASC) VISIBLE,
  INDEX `fk_congre_catSexo_idx` (`con_sexo` ASC) VISIBLE,
  INDEX `fk_congre_catEdoCivil_idx` (`con_edo_civil` ASC) VISIBLE,
  INDEX `fk_congre_catStatusCongre_idx` (`con_status_con` ASC) VISIBLE,
  INDEX `fk_congre_catNacion_idx` (`con_nacionalidad` ASC) VISIBLE,
  CONSTRAINT `fk_congre_catSexo`
    FOREIGN KEY (`con_sexo`)
    REFERENCES `bdconectate`.`cat_sexo` (`idsexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_congre_catEdoCivil`
    FOREIGN KEY (`con_edo_civil`)
    REFERENCES `bdconectate`.`cat_edo_civil` (`idedocivil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_congre_catStatusCongre`
    FOREIGN KEY (`con_status_con`)
    REFERENCES `bdconectate`.`cat_status_congregante` (`idstatus_con`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_congre_catNacion`
    FOREIGN KEY (`con_nacionalidad`)
    REFERENCES `bdconectate`.`cat_nacionalidad` (`idnacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdconectate`.`iglesia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdconectate`.`iglesia` ;

CREATE TABLE IF NOT EXISTS `bdconectate`.`iglesia` (
  `idiglesia` INT NOT NULL AUTO_INCREMENT,
  `iglesia_alias` VARCHAR(300) NOT NULL COMMENT 'alias significa nombre corto',
  `iglesia_nombre` VARCHAR(500) NOT NULL COMMENT 'nombre completo de la congracion',
  `iglesia_nom_corto` VARCHAR(100) NULL,
  `iglesia_nom_largo` VARCHAR(300) NULL,
  `iglesia_desc` VARCHAR(500) NULL,
  `ctrl_fecha_create` DATETIME NULL,
  `ctrl_fecha_update` DATETIME NOT NULL,
  `ctrl_user_mod` INT NOT NULL,
  PRIMARY KEY (`idiglesia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdconectate`.`correos_congregantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdconectate`.`correos_congregantes` ;

CREATE TABLE IF NOT EXISTS `bdconectate`.`correos_congregantes` (
  `idcorreo` INT NOT NULL AUTO_INCREMENT,
  `idcon` INT NOT NULL,
  `correo` VARCHAR(300) NOT NULL,
  `status` TINYINT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `ctrl_fecha_create` DATETIME NULL,
  `ctrl_fecha_update` DATETIME NOT NULL,
  `ctrl_user_mod` INT NOT NULL,
  PRIMARY KEY (`idcorreo`),
  INDEX `fk_correo_congre_idx` (`idcon` ASC) VISIBLE,
  CONSTRAINT `fk_correo_congre`
    FOREIGN KEY (`idcon`)
    REFERENCES `bdconectate`.`congregantes` (`idcon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdconectate`.`correos_iglesia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdconectate`.`correos_iglesia` ;

CREATE TABLE IF NOT EXISTS `bdconectate`.`correos_iglesia` (
  `idcorreo` INT NOT NULL AUTO_INCREMENT,
  `idiglesia` INT NOT NULL,
  `correo` VARCHAR(300) NOT NULL,
  `status` TINYINT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `ctrl_fecha_create` DATETIME NULL,
  `ctrl_fecha_update` DATETIME NOT NULL,
  `ctrl_user_mod` INT NOT NULL,
  PRIMARY KEY (`idcorreo`),
  INDEX `fk_correo_iglesia_idx` (`idiglesia` ASC) VISIBLE,
  CONSTRAINT `fk_correo_iglesia`
    FOREIGN KEY (`idiglesia`)
    REFERENCES `bdconectate`.`iglesia` (`idiglesia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdconectate`.`telefono_iglesia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdconectate`.`telefono_iglesia` ;

CREATE TABLE IF NOT EXISTS `bdconectate`.`telefono_iglesia` (
  `idtel_iglesia` INT NOT NULL AUTO_INCREMENT,
  `idiglesia` INT NOT NULL,
  `telefono` VARCHAR(100) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `ctrl_fecha_create` DATETIME NULL,
  `ctrl_fecha_update` DATETIME NOT NULL,
  `ctrl_user_mod` INT NOT NULL,
  PRIMARY KEY (`idtel_iglesia`),
  INDEX `fk_telefono_iglesia_idx` (`idiglesia` ASC) VISIBLE,
  CONSTRAINT `fk_telefono_iglesia`
    FOREIGN KEY (`idiglesia`)
    REFERENCES `bdconectate`.`iglesia` (`idiglesia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdconectate`.`cat_direccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdconectate`.`cat_direccion` ;

CREATE TABLE IF NOT EXISTS `bdconectate`.`cat_direccion` (
  `id_direccion` INT NOT NULL AUTO_INCREMENT,
  `d_codigo` VARCHAR(10) NOT NULL,
  `d_asenta` VARCHAR(150) NULL,
  `d_tipo_asenta` VARCHAR(150) NULL,
  `d_mnpio` VARCHAR(150) NULL,
  `d_estado` VARCHAR(150) NULL,
  `d_ciudad` VARCHAR(150) NULL,
  `d_CP` VARCHAR(10) NULL,
  `c_estado` VARCHAR(10) NULL,
  `c_oficina` VARCHAR(10) NULL,
  `c_CP` VARCHAR(10) NULL,
  `c_tipo_asenta` VARCHAR(10) NULL,
  `c_mnpio` VARCHAR(10) NULL,
  `id_asenta_cpcons` VARCHAR(10) NULL,
  `d_zona` VARCHAR(10) NULL,
  `c_cve_ciudad` VARCHAR(10) NULL,
  `ctrl_fecha_create` DATETIME NULL,
  `ctrl_fecha_update` DATETIME NOT NULL,
  `ctrl_user_mod` INT NOT NULL,
  PRIMARY KEY (`id_direccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdconectate`.`direccion_iglesia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdconectate`.`direccion_iglesia` ;

CREATE TABLE IF NOT EXISTS `bdconectate`.`direccion_iglesia` (
  `iddir_iglesia` INT NOT NULL AUTO_INCREMENT,
  `idiglesia` INT NOT NULL,
  `id_direccion` INT NOT NULL,
  `dir_calle` VARCHAR(300) NOT NULL,
  `dir_num_ext` VARCHAR(10) NULL,
  `dir_num_int` VARCHAR(10) NULL,
  `dir_entre_calles` VARCHAR(200) NULL,
  `ctrl_fecha_create` DATETIME NULL,
  `ctrl_fecha_update` DATETIME NOT NULL,
  `ctrl_user_mod` INT NOT NULL,
  PRIMARY KEY (`iddir_iglesia`),
  INDEX `fk_dirIglesia_iglesia_idx` (`idiglesia` ASC) VISIBLE,
  INDEX `fk_dirIgle_catDir_idx` (`id_direccion` ASC) VISIBLE,
  CONSTRAINT `fk_dirIglesia_iglesia`
    FOREIGN KEY (`idiglesia`)
    REFERENCES `bdconectate`.`iglesia` (`idiglesia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dirIgle_catDir`
    FOREIGN KEY (`id_direccion`)
    REFERENCES `bdconectate`.`cat_direccion` (`id_direccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdconectate`.`telefono_congregantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdconectate`.`telefono_congregantes` ;

CREATE TABLE IF NOT EXISTS `bdconectate`.`telefono_congregantes` (
  `idtel_congregante` INT NOT NULL AUTO_INCREMENT,
  `idcon` INT NOT NULL,
  `telefono` VARCHAR(100) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `ctrl_fecha_create` DATETIME NULL,
  `ctrl_fecha_update` DATETIME NOT NULL,
  `ctrl_user_mod` INT NOT NULL,
  PRIMARY KEY (`idtel_congregante`),
  INDEX `fk_telefono_congre_idx` (`idcon` ASC) VISIBLE,
  CONSTRAINT `fk_telefono_congre`
    FOREIGN KEY (`idcon`)
    REFERENCES `bdconectate`.`congregantes` (`idcon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdconectate`.`direccion_congregante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdconectate`.`direccion_congregante` ;

CREATE TABLE IF NOT EXISTS `bdconectate`.`direccion_congregante` (
  `iddir_iglesia` INT NOT NULL AUTO_INCREMENT,
  `idcon` INT NOT NULL,
  `id_direccion` INT NOT NULL,
  `dir_calle` VARCHAR(300) NOT NULL,
  `dir_num_ext` VARCHAR(10) NULL,
  `dir_num_int` VARCHAR(10) NULL,
  `dir_entre_calles` VARCHAR(200) NULL,
  `ctrl_fecha_create` DATETIME NULL,
  `ctrl_fecha_update` DATETIME NOT NULL,
  `ctrl_user_mod` INT NOT NULL,
  PRIMARY KEY (`iddir_iglesia`),
  INDEX `fk_dirCongre_congre_idx` (`idcon` ASC) VISIBLE,
  INDEX `fk_dirCongre_catDir_idx` (`id_direccion` ASC) VISIBLE,
  CONSTRAINT `fk_dirCongre_congre`
    FOREIGN KEY (`idcon`)
    REFERENCES `bdconectate`.`congregantes` (`idcon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dirCongre_catDir`
    FOREIGN KEY (`id_direccion`)
    REFERENCES `bdconectate`.`cat_direccion` (`id_direccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdconectate`.`congregante_iglesia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdconectate`.`congregante_iglesia` ;

CREATE TABLE IF NOT EXISTS `bdconectate`.`congregante_iglesia` (
  `idcon_igle` INT NOT NULL AUTO_INCREMENT,
  `idcon` INT NOT NULL,
  `idiglesia` INT NOT NULL,
  `activo` TINYINT NOT NULL,
  `ctrl_fecha_create` DATETIME NULL,
  `ctrl_fecha_update` DATETIME NOT NULL,
  `ctrl_user_mod` INT NOT NULL,
  PRIMARY KEY (`idcon_igle`),
  INDEX `fk_congreIgle_congre_idx` (`idcon` ASC) VISIBLE,
  INDEX `fk_congreIgle_iglesia_idx` (`idiglesia` ASC) VISIBLE,
  CONSTRAINT `fk_congreIgle_congre`
    FOREIGN KEY (`idcon`)
    REFERENCES `bdconectate`.`congregantes` (`idcon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_congreIgle_iglesia`
    FOREIGN KEY (`idiglesia`)
    REFERENCES `bdconectate`.`iglesia` (`idiglesia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdconectate`.`ministerios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdconectate`.`ministerios` ;

CREATE TABLE IF NOT EXISTS `bdconectate`.`ministerios` (
  `idministerio` INT NOT NULL AUTO_INCREMENT,
  `idiglesia` INT NOT NULL COMMENT 'se va agregar de cada congregacion su catalago de ministerios',
  `ministerio_nombre` VARCHAR(100) NOT NULL,
  `ministerio_desc_corta` VARCHAR(45) NOT NULL,
  `ministerio_desc` VARCHAR(250) NOT NULL,
  `ministerio_act` TINYINT NOT NULL,
  `ctrl_fecha_create` DATETIME NULL,
  `ctrl_fecha_update` DATETIME NOT NULL,
  `ctrl_user_mod` INT NOT NULL,
  PRIMARY KEY (`idministerio`),
  INDEX `fk_ministerio_iglesia_idx` (`idiglesia` ASC) VISIBLE,
  CONSTRAINT `fk_ministerio_iglesia`
    FOREIGN KEY (`idiglesia`)
    REFERENCES `bdconectate`.`iglesia` (`idiglesia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdconectate`.`cargo_ministerio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdconectate`.`cargo_ministerio` ;

CREATE TABLE IF NOT EXISTS `bdconectate`.`cargo_ministerio` (
  `idcargo_ministerio` INT NOT NULL AUTO_INCREMENT,
  `idministerio` INT NOT NULL,
  `cargo_min_nombre` VARCHAR(45) NOT NULL,
  `cargo_min_desc` VARCHAR(250) NOT NULL,
  `ctrl_fecha_create` DATETIME NULL,
  `ctrl_fecha_update` DATETIME NOT NULL,
  `ctrl_user_mod` INT NOT NULL,
  PRIMARY KEY (`idcargo_ministerio`),
  INDEX `fk_cargoMinisterio_minis_idx` (`idministerio` ASC) VISIBLE,
  CONSTRAINT `fk_cargoMinisterio_minis`
    FOREIGN KEY (`idministerio`)
    REFERENCES `bdconectate`.`ministerios` (`idministerio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdconectate`.`congregante_ministerio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdconectate`.`congregante_ministerio` ;

CREATE TABLE IF NOT EXISTS `bdconectate`.`congregante_ministerio` (
  `idcon_min` INT NOT NULL AUTO_INCREMENT,
  `idcon` INT NOT NULL COMMENT 'el id del congregante ',
  `idministerio` INT NOT NULL COMMENT 'id del ministerio ',
  `idcargomini` INT NOT NULL COMMENT 'el cargo puede ser coordinador , director ,',
  `ctrl_fecha_create` DATETIME NULL,
  `ctrl_fecha_update` DATETIME NOT NULL,
  `ctrl_user_mod` INT NOT NULL,
  PRIMARY KEY (`idcon_min`),
  INDEX `fk_congreMinis_congre_idx` (`idcon` ASC) VISIBLE,
  INDEX `fk_congreMinis_minis_idx` (`idministerio` ASC) VISIBLE,
  INDEX `fk_congreMinis_cargoMinis_idx` (`idcargomini` ASC) VISIBLE,
  CONSTRAINT `fk_congreMinis_congre`
    FOREIGN KEY (`idcon`)
    REFERENCES `bdconectate`.`congregantes` (`idcon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_congreMinis_minis`
    FOREIGN KEY (`idministerio`)
    REFERENCES `bdconectate`.`ministerios` (`idministerio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_congreMinis_cargoMinis`
    FOREIGN KEY (`idcargomini`)
    REFERENCES `bdconectate`.`cargo_ministerio` (`idcargo_ministerio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdconectate`.`formacion_congregantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdconectate`.`formacion_congregantes` ;

CREATE TABLE IF NOT EXISTS `bdconectate`.`formacion_congregantes` (
  `idfor_congre` INT NOT NULL AUTO_INCREMENT,
  `idcon` INT NOT NULL,
  `for_con_estudiante` TINYINT NOT NULL COMMENT 'valida si es estudiante SI/NO 1/0',
  `for_con_trabajador` TINYINT NOT NULL COMMENT 'valida si tiene trabajo SI/NO 1/0',
  `ctrl_fecha_create` DATETIME NULL,
  `ctrl_fecha_update` DATETIME NOT NULL,
  `ctrl_user_mod` INT NOT NULL,
  PRIMARY KEY (`idfor_congre`),
  INDEX `fk_formacion_congre_idx` (`idcon` ASC) VISIBLE,
  CONSTRAINT `fk_formacion_congre`
    FOREIGN KEY (`idcon`)
    REFERENCES `bdconectate`.`congregantes` (`idcon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdconectate`.`cat_status_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdconectate`.`cat_status_usuario` ;

CREATE TABLE IF NOT EXISTS `bdconectate`.`cat_status_usuario` (
  `idcat_status_usuario` INT NOT NULL AUTO_INCREMENT,
  `clave` VARCHAR(45) NOT NULL,
  `desc` VARCHAR(150) NOT NULL,
  `ctrl_fecha_create` DATETIME NULL,
  `ctrl_fecha_update` DATETIME NOT NULL,
  `ctrl_user_mod` INT NOT NULL,
  PRIMARY KEY (`idcat_status_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdconectate`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdconectate`.`usuario` ;

CREATE TABLE IF NOT EXISTS `bdconectate`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `user_id_con` INT NOT NULL,
  `user_email` VARCHAR(300) NULL COMMENT 'puede ser que no tenga email (gente adulta)',
  `user_matricula` VARCHAR(10) NOT NULL,
  `user_pwd` VARCHAR(45) NOT NULL,
  `user_status` INT NOT NULL,
  `ctrl_fecha_create` DATETIME NULL,
  `ctrl_fecha_update` DATETIME NOT NULL,
  `ctrl_user_mod` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `user_id_con_UNIQUE` (`user_id_con` ASC) VISIBLE,
  UNIQUE INDEX `user_email_UNIQUE` (`user_email` ASC) VISIBLE,
  UNIQUE INDEX `user_matricula_UNIQUE` (`user_matricula` ASC) VISIBLE,
  INDEX `fk_cat_status_usu_idx` (`user_status` ASC) VISIBLE,
  CONSTRAINT `fk_cat_status_usu`
    FOREIGN KEY (`user_status`)
    REFERENCES `bdconectate`.`cat_status_usuario` (`idcat_status_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdconectate`.`cat_rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdconectate`.`cat_rol` ;

CREATE TABLE IF NOT EXISTS `bdconectate`.`cat_rol` (
  `idcat_rol` INT NOT NULL AUTO_INCREMENT,
  `clave_rol` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `desc` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL,
  `ctrl_fecha_create` DATETIME NULL,
  `ctrl_fecha_update` DATETIME NOT NULL,
  `ctrl_user_mod` INT NOT NULL,
  PRIMARY KEY (`idcat_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdconectate`.`usuario_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdconectate`.`usuario_roles` ;

CREATE TABLE IF NOT EXISTS `bdconectate`.`usuario_roles` (
  `id_usu_rol` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `usu_cat_rol` INT NOT NULL,
  `ctrl_fecha_create` DATETIME NULL,
  `ctrl_fecha_update` DATETIME NOT NULL,
  `ctrl_user_mod` INT NOT NULL,
  PRIMARY KEY (`id_usu_rol`),
  INDEX `fk_usuario_cat_rol_idx` (`usu_cat_rol` ASC) VISIBLE,
  INDEX `fk_usuario_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bdconectate`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_cat_rol`
    FOREIGN KEY (`usu_cat_rol`)
    REFERENCES `bdconectate`.`cat_rol` (`idcat_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
